name: Lint

on:
  pull_request:

jobs:
  lint:
    uses: drasi-project/.github/.github/workflows/rust-lint.yaml@main
    with:
      install-jq: true
      install-protobuf: true
      clippy-command: "cargo clippy --locked --all-targets -- -D warnings"
      clippy-args: ""
      fmt-command: "make fmt-check"
