name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: drasi-project/.github/.github/workflows/rust-lint.yaml@rust195
    with:
      install-jq: true
      install-protobuf: true
      clippy-command: "make clippy"
      fmt-command: "make fmt-check"
