name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: drasi-project/.github/.github/workflows/rust-unit-test.yaml@rust195
    with:
      install-jq: true
      install-protobuf: true
